# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20180224_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='maximum_marks',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6, verbose_name='Maximum Marks'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='html',
            field=models.TextField(verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is this answer correct?'),
        ),
    ]
